### ISSUE TITLE
"ö" turns into "\xf6"

### ISSUE THREAD

**Issue by Daschi1** [Carleslc/Simple-YAML#11]
When writing an "ö" in a config it turns into "\xf6";

My code for writing:
```java
final File file = new File("config.yml");
try {
    final YamlFile yamlFile = new YamlFile(file);
    if (!yamlFile.exists()) {
        yamlFile.createNewFile(true);
    }
    yamlFile.loadWithComments();
    yamlFile.set("test", "ö");
    yamlFile.saveWithComments();
} catch (final IOException | InvalidConfigurationException exception) {
    exception.printStackTrace();
}
```
The config:
```yaml
test: "\xf6"
```
The code for reading (output: "?"):
```java
final File file = new File("config.yml");
final YamlFile yamlFile = new YamlFile(file);
try {
    yamlFile.loadWithComments();
} catch (final InvalidConfigurationException | IOException exception) {
    exception.printStackTrace();
}
System.out.println(yamlFile.getString("test"));
```

**Comment by Carleslc** [comment]
I cannot reproduce it. Check that the encoding of your `config.yml` is UTF-8 in your text editor.

Also check the encoding of the YamlFile:

```java
YamlFile yamlFile = new YamlFile("test-encoding.yml");

System.out.println("Default Charset: " + Charset.defaultCharset());
System.out.println("Allow Unicode: " + FileConfiguration.SYSTEM_UTF);

yamlFile.createNewFile(false);
yamlFile.load();

yamlFile.set("ö", "ö");
yamlFile.set("umlauts", "öüäß");
yamlFile.set("hiragana", "ひらがな");
yamlFile.set("kanji", "漢字");
yamlFile.set("emoji", "\uD83D\uDE01");

yamlFile.getValues(true).forEach((key, value) -> System.out.println(key + ": " + value));

yamlFile.save();
```

This is my output:

```
Default Charset: UTF-8
Allow Unicode: true
ö: ö
umlauts: öüäß
hiragana: ひらがな
kanji: 漢字
emoji: 😁
```

**Comment by Daschi1** [comment]
Thanks for your reply. The encoding of the config is displayed as `UTF-8`.
I have run your code and this is my output:
```
Default Charset: windows-1252
Allow Unicode: false
�: �
umlauts: ����
hiragana: ????
kanji: ??
emoji: ?
```

**Comment by Carleslc** [comment]
I'm using MacOS. Your system or Java VM default charset does not accept Unicode characters and this API uses the default charset encoding to load/save files.

Some methods and fields were deprecated because of this, like the `FileConfiguration.SYSTEM_UTF` in my code above. I've updated the API to use UTF-8 by default, with an option to change the charset. I've also removed deprecated code related to encoding issues (as per Bukkit newest FileConfiguration).

Update to [v1.6.1](https://github.com/Carleslc/Simple-YAML/releases/tag/1.6.1) and run the code at [`YamlEncodingTest`](https://github.com/Carleslc/Simple-YAML/blob/master/src/org/simpleyaml/test/YamlEncodingTest.java) to ensure it is working on your system.

If desired, you can change the encoding to use the default with:

```java
yamlFile.options().charset(Charset.defaultCharset());
```

**Comment by Daschi1** [comment]
It is working now. Everything is getting wrote and outputted properly now.
Thank you so much!
