### ISSUE TITLE
file.getName();

### ISSUE THREAD

**Issue by proxytimeout** [Carleslc/Simple-YAML#32]
When ever I try to get a File name with file.getName(); it returns nothing.

**Comment by portlek** [comment]
it's not returning the file name. it's for the current path's section name.

**Comment by Carleslc** [comment]
Use `yamlFile.getConfigurationFile().getName()` to get the file name, or `yamlFile.getFilePath()` to get the absolute path.

`getName` is a method of `ConfigurationSection` ([docs](https://carleslc.me/Simple-YAML/doc/Simple-Configuration/org/simpleyaml/configuration/ConfigurationSection.html#getName())) that returns the name of the configuration section. `YamlFile` implements `ConfigurationSection` (is the file's root section), so `yamlFile.getName()` returns the same as `yamlFile.getRoot().getName()`, which is blank because root path is blank (`yamlFile.getCurrentPath()` is blank too, for the same reason).

For instance, `yamlFile.getConfigurationSection("test").getName()` will return _`test`_.
