### ISSUE TITLE
Weird behavior of Side comments

### ISSUE THREAD

**Issue by HSGamer** [Carleslc/Simple-YAML#42]
I wrote a program to test the comment feature of YAML
* **The code**
```java
        // Create new YAML file with relative path
        saveResource("test.yml", true);
        final YamlFile yamlFile = new YamlFile(new File(getDataFolder(), "test.yml"));

        try {
            yamlFile.createOrLoadWithComments();
        } catch (final Exception e) {
            e.printStackTrace();
        }

        System.out.println("test-comment value: " + yamlFile.getString("test-comment"));
        System.out.println("test-comment side comment: " + yamlFile.getComment("test-comment", CommentType.SIDE));
        System.out.println("test-comment1 value: " + yamlFile.getString("test-comment1"));
        System.out.println("test-comment1 side comment: " + yamlFile.getComment("test-comment1", CommentType.SIDE));

        try {
            yamlFile.save();
        } catch (final IOException e) {
            e.printStackTrace();
        }
```
* **test.yml**
```yaml
test-comment: 'value' # comment
test-comment1: 'test# value2' # comment
```
* **Output**
```
test-comment value: value
test-comment side comment: comment
test-comment1 value: test# value2
test-comment1 side comment: value2'comment
```
* **test.yml** after running the code
```yaml
test-comment: value # comment
test-comment1: test# value2# value2' # comment
```
---
The **output** was supposed to be
```
test-comment value: value
test-comment side comment: comment
test-comment1 value: test# value2
test-comment1 side comment: comment
```
And **test.yml** should not be changed

**Comment by HSGamer** [comment]
Maybe the regex for side comments should be changed

**Comment by re-ovo** [comment]
When will the next version be released? This bug will cause the configuration file to become more and more bloated and eventually crash

![image](https://user-images.githubusercontent.com/21152113/154786331-a5d19e1e-9d09-4c60-afb5-72502373bd9e.png)

**Comment by Carleslc** [comment]
> When will the next version be released? This bug will cause the configuration file to become more and more bloated and eventually crash

Probably in the next days (less than a week).

In the meanwhile, as this is a bug related to the comment parser if you don't need comments at all you can load your file with `load` instead `loadWithComments` and this bug will not happen (just make sure you don't have comments in your file because they would be removed).

**Comment by Carleslc** [comment]
Sorry for the delay, it has involved more work than the thought initially.

[Version 1.8](https://github.com/Carleslc/Simple-YAML/releases/tag/1.8) is now released, solving this issue and adding other useful features too.

I've removed the side regex entirely, improving the comment parser to handle quotes and literal strings. The output is now the expected, since having a # in a string value is not an issue anymore.

I'm closing the issue. If you encounter a related problem with this issue or have any doubt feel free to reopen it.
