### ISSUE TITLE
Auto updates

### ISSUE THREAD

**Issue by creatorfromhell** [Carleslc/Simple-YAML#51]
Does this library automatically add nodes from the default resource to the existing yaml file if they're not currently present?

**Comment by Carleslc** [comment]
Yes, this is what [`copyDefaults(true)`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/file/YamlConfigurationOptions.html#copyDefaults-boolean-) does (it is set to true by default since version 1.6.1), just ensure you add your default values using [`addDefault`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/MemoryConfiguration.html#addDefault-java.lang.String-java.lang.Object-), [`setDefaults`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/MemoryConfiguration.html#setDefaults-org.simpleyaml.configuration.Configuration-) or [`addDefaults`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/MemoryConfiguration.html#addDefaults-org.simpleyaml.configuration.Configuration-).

See the [example](https://github.com/Carleslc/Simple-YAML/blob/master/Simple-Yaml/src/test/java/org/simpleyaml/examples/YamlExample.java).

**Comment by Carleslc** [comment]
I'm closing this issue as it is answered. Reopen it if there are any doubts.
