### ISSUE TITLE
There is a bug when i set the list

### ISSUE THREAD

**Issue by OMAR-3OOV** [Carleslc/Simple-YAML#61]
so basically I used the library for a few days, and I found out that when I have a list already and try to add an element to it, something weird happens, so I create the List first by using `config.set("key", ArrayList<String>(""))` so first I want to create empty list.
but in the YML file it's not empty, so the bug is when I try to add  an element like this: 

```java
List<String> list = ArrayList<String>(config.getStringList("key"), ("newElement"));

config.set("key", list);
config.save()
```

it displayed in the file like this

```yml
-  - 'newElement'
- 'oldElements'

```
it's so weird bug...

**Comment by Carleslc** [comment]
As stated, that is the intended behaviour. Thank you @EverNife for the answer.

With `config.set("key", Arrays.asList(config.getStringList("key"), "newElement"))` you're creating a list of lists instead of appending the previous elements. To append the previous elements you must use [`addAll`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#addAll-java.util.Collection-).

Example to add elements to a list:

```java
// Create the YamlFile
YamlFile config = new YamlFile("examples/test61.yml");

// Create a new config file if it does not exist or load its contents otherwise
config.createOrLoad();

// Set a new empty list
config.set("key", new ArrayList<String>());

// Get the previously set list (copy)
List<String> list = config.getStringList("key");

// Add several elements to the list
list.addAll(Arrays.asList("oldElement1", "oldElement2"));

// Add single element to the list
list.add("newElement");

// Update the list elements
config.set("key", list);

// You can also add elements with list indexing!
config.set("key[-1]", "lastElement");

// Save the configuration file
config.save();
```

```yaml
key:
  - oldElement1
  - oldElement2
  - newElement
  - lastElement
```
