### ISSUE TITLE
Enhancement/Feature Request - addDefault() enforce quote style

### ISSUE THREAD

**Issue by omega0verride** [Carleslc/Simple-YAML#65]
It would be great if we could use this same syntax for addDefault()
yamlFile.set("quotes.custom", "This is double quote style", QuoteStyle.DOUBLE);

I could not find any documentation on how to get this to work, looking at the code we might have to modify MemoryConfiguration.

A workaround would be combining isSet() and set() but that does not look like a great idea.

**Comment by Carleslc** [comment]
If you want to set a single default value with a custom quote style you can wrap the value with a `QuoteValue` like this:

```java
yamlFile.addDefault("default", new QuoteValue<String>("test", QuoteStyle.DOUBLE));
```

If you want to write all default strings with double quotes you can set your own configuration defaults with the [`setDefaults`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/MemoryConfiguration.html#setDefaults-org.simpleyaml.configuration.Configuration-) method, for instance you can use a `YamlConfiguration` instance for your defaults (instead of the default `MemoryConfiguration`), so you can use the [`set`](https://carleslc.me/Simple-YAML/doc/org/simpleyaml/configuration/file/YamlConfiguration.html#set-java.lang.String-java.lang.Object-org.simpleyaml.configuration.implementation.api.QuoteStyle-) method for your defaults:

```java
YamlConfiguration defaults = new YamlConfiguration();

defaults.options().quoteStyleDefaults().setQuoteStyle(String.class, QuoteStyle.DOUBLE);

defaults.set("default", "test");

yamlFile.setDefaults(defaults);
```

Output:
```yaml
default: "test"
```

**Comment by Carleslc** [comment]
Note that quote styles of default values will only be applied the first time when the value does not exist in the file, because when the path already exists it is not a default value anymore, so if you want to preserve the quote style you can either:

Use the `set` method instead of `addDefault`:

```java
private static <T> void setDefault(YamlFile yamlFile, String path, T value, QuoteStyle quoteStyle) {
    if (!yamlFile.isSet(path)) {
        yamlFile.set(path, value, quoteStyle);
    }
}
```

```java
setDefault(yamlFile, "default", "test", QuoteStyle.DOUBLE);
```

Or use the `addDefault` or `setDefaults` as usual like in my previous message and then a function to set the quote style of your desired values for already existing values, without changing their values:

```java
private static void wrapValues(YamlFile yamlFile, QuoteStyle quoteStyle, String... paths) {
    for (String path : paths) {
        if (yamlFile.isSet(path)) {
            yamlFile.set(path, yamlFile.get(path), quoteStyle);
        }
    }
}
```

```java
wrapValues(yamlFile, QuoteStyle.DOUBLE, "default");
```

Instead of using static functions you could also extend `YamlFile` with your own methods.

**Comment by omega0verride** [comment]
Thank you @Carleslc!
This works like a charm for my requirements:
`yamlFile.addDefault("default", new QuoteValue<>("test", QuoteStyle.DOUBLE));`
