### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.DumperOptions.setIndentWithIndicator(boolean)'

### ISSUE THREAD

**Issue by thelipe7** [Carleslc/Simple-YAML#68]
I am getting the following error when creating a config:
![image](https://user-images.githubusercontent.com/101154133/203407279-6b85541e-03e3-4e55-b643-4922bc426184.png)

My code:
![image](https://user-images.githubusercontent.com/101154133/203407315-6732edfd-4b73-4288-af90-f46a193463fd.png)

**Comment by Carleslc** [comment]
This is not a Simple-YAML bug; it is a known issue related to a dependency clash between Velocity and Simple-YAML.

Velocity uses an older version of snakeyaml (1.26) than this library requires (1.30 or above, latest version uses 1.32). Because of this, there is a dependency clash, so even if the correct version is built with maven into your plugin through Simple-Yaml, in runtime at the moment of loading your plugin the first loaded version prevails, which sadly happens to be the older one loaded by the Velocity server.

See [this comment](https://github.com/Carleslc/Simple-YAML/issues/67#issuecomment-1296395173) to read a more detailed explanation for the error and its solution, which is relocation to differentiate both versions in runtime using different classpaths.

**Comment by Carleslc** [comment]
Since [1.8.3](https://github.com/Carleslc/Simple-YAML/releases/) the manual relocation is not needed as it is already included.
Add the relocation in 1.8.2 or update to 1.8.3.
I'm closing the issue. Comment if you have any doubts.

**Comment by thelipe7** [comment]
Thanks :)
