### ISSUE TITLE
Custom Domain Jitpack Deployment

### ISSUE THREAD

**Issue by TheRealRyGuy** [Carleslc/Simple-YAML#77]
Something's flawed with jitpack deployment 
https://jitpack.io/com/github/carleslc/Simple-YAML/Simple-Yaml/1.8.4/Simple-Yaml-1.8.4.pom exists
https://jitpack.io/me/carleslc/Simple-YAML/Simple-Yaml/1.8.4/Simple-Yaml-1.8.4.pom doesn't
Essentially means any [dependent](https://github.com/PurpurMC/Purpur/actions/runs/5349927678/jobs/9724140660#step:7:530) can't build logically using the given custom domain

**Comment by Carleslc** [comment]
This seems related to #70. I think I solved it removing the build from Jitpack and then triggering it again.

I guess it is something with Jitpack, because when I triggered the build it was correct and the pom in https://jitpack.io/me/carleslc/Simple-YAML/Simple-Yaml/1.8.4/Simple-Yaml-1.8.4.pom existed, but now suddenly it doesn't, so it started causing problems to retrieve the dependency. Maybe is something with Jitpack cache? Build passed and is green (https://jitpack.io/#me.carleslc/Simple-YAML), but the pom related to that version does not exist anymore, and because the build is green in Jitpack, it does not trigger a new build by its own.

However, `com.github.Carleslc` groupId still works, so it can be used as an alternative to retrieve the dependency.

**Comment by AkramLZ** [comment]
> This seems related to #70. I think I solved it removing the build from Jitpack and then triggering it again.
> 
> I guess it is something with Jitpack, because when I triggered the build it was correct and the pom in https://jitpack.io/me/carleslc/Simple-YAML/Simple-Yaml/1.8.4/Simple-Yaml-1.8.4.pom existed, but now suddenly it doesn't, so it started causing problems to retrieve the dependency. Maybe is something with Jitpack cache? Build passed and is green (https://jitpack.io/#me.carleslc/Simple-YAML), but the pom related to that version does not exist anymore, and because the build is green in Jitpack, it does not trigger a new build by its own.
> 
> However, `com.github.Carleslc` groupId still works, so it can be used as an alternative to retrieve the dependency.

You can just use `com.github.Carleslc` instead of a custom domain since it doesn't really matter to have a custom domain for it and more stable.

**Comment by jaapieaapie1** [comment]
One of my dependencies which I do not control uses the me.carleslc custom domain resulting in gradle not being able to resolve it when building my project.

**Comment by Carleslc** [comment]
> One of my dependencies which I do not control uses the me.carleslc custom domain resulting in gradle not being able to resolve it when building my project.

Now https://jitpack.io/me/carleslc/Simple-YAML/Simple-Yaml/1.8.4/Simple-Yaml-1.8.4.pom is working again (I've triggered a new build). But still don't know why jitpack removes files unexpectedly.

**Comment by Carleslc** [comment]
Since it seems to be more stable, `com.github.Carleslc.Simple-YAML` is now specified in the README.
But `me.carleslc.Simple-YAML` groupId is still valid and supported.
